theme: jekyll-theme-slate
title: Welcome to the Frobodaggins Webpage of Wondery
description: Just like the light you see from the stars you see at night that took millions of  years to get to you, those stars are dead, along with your dreams.
